IF NOT EXISTS(SELECT * FROM sys.objects WHERE name = 'TB_DESC_PRODUTO') 

CREATE TABLE [dbo].[TB_DESC_PRODUTO](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[DESCRICAO] [varchar](100) NOT NULL,
 CONSTRAINT [PK_TB_DESC_PRODUTO] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)
) ON [PRIMARY]

GO 