
IF NOT EXISTS(SELECT * FROM sys.objects WHERE name = 'TB_ESTOQUE')  

CREATE TABLE [dbo].[TB_ESTOQUE](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[DESCRICAO] [varchar](100) NOT NULL,
 CONSTRAINT [PK_TB_ESTOQUE] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)
) ON [PRIMARY]

GO


