
IF NOT EXISTS(SELECT * FROM sys.objects WHERE name = 'TB_FABRICANTE')  

CREATE TABLE [dbo].[TB_FABRICANTE](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[DESCRICAO] [varchar](100) NOT NULL,
 CONSTRAINT [PK_TB_FABRICANTE] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)
) ON [PRIMARY]

GO



