-- =============================================
-- Author:		<CHARLES GUEDES>
-- Create date: <15/04/2014>
-- Description:	<PROCEDURE PARA INSERIR DADOS NA TABELA>
-- =============================================
CREATE PROCEDURE SP_INSERIR_DESCR_FABRICANTE
@DESCRICAO varchar(100)
AS
BEGIN
INSERT INTO TB_FABRICANTE(DESCRICAO)
VALUES(@DESCRICAO)
END

--TESTE
EXEC SP_INSERIR_DESCR_FABRICANTE 'FIAT'
EXEC SP_INSERIR_DESCR_FABRICANTE 'VOLKSWAGEN'
EXEC SP_INSERIR_DESCR_FABRICANTE 'CHEVROLET'
EXEC SP_INSERIR_DESCR_FABRICANTE 'FORD'
EXEC SP_INSERIR_DESCR_FABRICANTE 'PEGEOUT'
EXEC SP_INSERIR_DESCR_FABRICANTE 'CITROEN'
EXEC SP_INSERIR_DESCR_FABRICANTE 'HONDA'
EXEC SP_INSERIR_DESCR_FABRICANTE 'NISSAN'
EXEC SP_INSERIR_DESCR_FABRICANTE 'HYNDAI'
EXEC SP_INSERIR_DESCR_FABRICANTE 'TOYOTA'
EXEC SP_INSERIR_DESCR_FABRICANTE 'CHERY'
EXEC SP_INSERIR_DESCR_FABRICANTE 'RENAULT'

--SELECT * FROM TB_FABRICANTE 


