-- =============================================
-- Author:		<CHARLES GUEDES>
-- Create date: <15/04/2014>
-- Description:	<PROCEDURE PARA INSERIR DADOS NA TABELA>
-- =============================================
CREATE PROCEDURE SP_INSERIR_DESCR_PROD

@DESCRICAO VARCHAR(100)
AS
BEGIN
INSERT INTO TB_DESC_PRODUTO(DESCRICAO)
VALUES(@DESCRICAO)
END


EXEC SP_INSERIR_DESCR_PROD "PARACHOQUE"
EXEC SP_INSERIR_DESCR_PROD "PARALAMA"
EXEC SP_INSERIR_DESCR_PROD "PORTA"
EXEC SP_INSERIR_DESCR_PROD "CAPÔ"
EXEC SP_INSERIR_DESCR_PROD "GRADE"
EXEC SP_INSERIR_DESCR_PROD "TAMPA"
EXEC SP_INSERIR_DESCR_PROD "PAINEL FRONTAL"
EXEC SP_INSERIR_DESCR_PROD "MINI"
EXEC SP_INSERIR_DESCR_PROD "PONTA DE LONGARINA"
EXEC SP_INSERIR_DESCR_PROD "LATERAL TRASEIRA"
EXEC SP_INSERIR_DESCR_PROD "FAROL"
EXEC SP_INSERIR_DESCR_PROD "LANTERNA"
EXEC SP_INSERIR_DESCR_PROD "FAROL MILHA"
EXEC SP_INSERIR_DESCR_PROD "SUPORTE DE RADIADOR"
EXEC SP_INSERIR_DESCR_PROD "NOVO PRODUTO" 


