-- =============================================
-- Author:		<CHARLES GUEDES>
-- Create date: <18/04/2014>
-- Description:	<PROCEDURE PARA INSERIR DADOS NA TABELA>
-- =============================================
CREATE PROCEDURE SP_INSERIR_DESC_PRODUTO
@DESCRICAO varchar(100)
AS
BEGIN
INSERT INTO TB_DESC_PRODUTO(DESCRICAO)
VALUES(@DESCRICAO)
END

--TESTE
EXEC SP_INSERIR_DESC_PRODUTO 'NOVO PRODUTO'
EXEC SP_INSERIR_DESC_PRODUTO 'PARACHOQUE'
EXEC SP_INSERIR_DESC_PRODUTO 'PARALAMA'
EXEC SP_INSERIR_DESC_PRODUTO 'PORTA'
EXEC SP_INSERIR_DESC_PRODUTO 'CAPÔ'
EXEC SP_INSERIR_DESC_PRODUTO 'GRADE'
EXEC SP_INSERIR_DESC_PRODUTO 'TAMPA'
EXEC SP_INSERIR_DESC_PRODUTO 'ALMA/VIGA'
EXEC SP_INSERIR_DESC_PRODUTO 'PAINEL FRONTAL'
EXEC SP_INSERIR_DESC_PRODUTO 'MINI'
EXEC SP_INSERIR_DESC_PRODUTO 'PONTA DE LONGARINA'
EXEC SP_INSERIR_DESC_PRODUTO 'LATERAL TRASEIRA'
EXEC SP_INSERIR_DESC_PRODUTO 'FAROL'
EXEC SP_INSERIR_DESC_PRODUTO 'LANTERNA'
EXEC SP_INSERIR_DESC_PRODUTO 'FAROL MILHA'
EXEC SP_INSERIR_DESC_PRODUTO 'SUPORTE DE RADIADOR'



--SELECT * FROM TB_DESC_PRODUTO 


