-- =============================================
-- Author:		<CHARLES GUEDES>
-- Create date: <19/04/2014>
-- Description:	<PROCEDURE PARA INSERIR DADOS NA TABELA>
-- =============================================
CREATE PROCEDURE SP_INSERIR_COR
@DESCRICAO varchar(100)
AS
BEGIN
INSERT INTO TB_COR(DESCRICAO)
VALUES(@DESCRICAO)
END

--TESTE
EXEC SP_INSERIR_COR 'NOVA COR'
EXEC SP_INSERIR_COR 'AMARELO'
EXEC SP_INSERIR_COR 'AZUL'
EXEC SP_INSERIR_COR 'BRANCO'
EXEC SP_INSERIR_COR 'CINZA'
EXEC SP_INSERIR_COR 'PRATA'
EXEC SP_INSERIR_COR 'PRETO'
EXEC SP_INSERIR_COR 'VERDE'
EXEC SP_INSERIR_COR 'VERMELHO'
EXEC SP_INSERIR_COR 'LARANJA'
