-- =============================================
-- Author:		<CHARLES GUEDES>
-- Create date: <20/04/2014>
-- Description:	<PROCEDURE PARA INSERIR DADOS NA TABELA>
-- =============================================
CREATE PROCEDURE SP_LISTAR_PRODUTOS
AS
BEGIN

SELECT E.DESCRICAO ESTOQUE, D.DESCRICAO PRODUTO, P.ID, P.ESTADO_PECA ESTADO_PECA, P.QUANTIDADE, P.ANO, P.VALOR_UNITARIO VALOR, F.DESCRICAO FABRICANTE, M.DESCRICAO MODELO, C.DESCRICAO COR, P.POSICAO_PECA POSICAO, LEFT (P.OBSERVACAO, 30)OBSERVACAO 
FROM TB_PRODUTO P
INNER JOIN TB_DESC_PRODUTO D
ON P.ID_DESC_PROD = D.ID 
INNER JOIN TB_FABRICANTE F 
ON P.ID_FABRICANTE = F.ID
INNER JOIN TB_MODELO M 
ON P.ID_MODELO = M.ID
INNER JOIN TB_COR C
ON P.ID_COR = C.ID 
INNER JOIN TB_ESTOQUE E
ON P.ID_ESTOQUE = E.ID  
END

--EXEC SP_LISTAR_PRODUTOS 646