-- =============================================
-- Author:		<CHARLES GUEDES>
-- Create date: <20/04/2014>
-- Description:	<PROCEDURE PARA INSERIR DADOS NA TABELA>
-- =============================================
CREATE PROCEDURE SP_SALVAR_PRODUTO
@ANO INT,
@ID_COR INT,
@ESTADO_PECA VARCHAR(50),
@QUANTIDADE INT,
@VALOR_UNITARIO DECIMAL(18,2),
@ID_ESTOQUE INT,
@ID_FABRICANTE INT,
@ID_DESC_PROD INT,
@OBSERVACAO VARCHAR(500),
@POSICAO_PECA VARCHAR(50),
@ID_MODELO INT

AS
BEGIN
INSERT INTO TB_PRODUTO(ANO,ID_COR,ESTADO_PECA,QUANTIDADE,VALOR_UNITARIO,ID_ESTOQUE,ID_FABRICANTE,ID_DESC_PROD,OBSERVACAO,POSICAO_PECA,ID_MODELO)
VALUES(@ANO,@ID_COR,@ESTADO_PECA,@QUANTIDADE,@VALOR_UNITARIO,@ID_ESTOQUE,@ID_FABRICANTE,@ID_DESC_PROD,@OBSERVACAO,@POSICAO_PECA,@ID_MODELO)
END
